/*
 * Description: This macro is used for the image reconstruction using the Siemens reconstruction method. 
 *
 *
 * Input: 
 *
 *
 * Procedure:
 *
 *
 * Functions:
 *
 *
 * Editor: Bo Ma
 *
 * Date: 2018.12.07
 *
 */




//void Image_reconstruction_Simens( string patient_name,string inputFolder, string path_norm_sino,string frame_time)
void Image_reconstruction_Simens()
{

  int nsubsets=2;
  int niterations=32;



  Simens_recon( niterations, nsubsets);

  gApplication->Terminate();


}



//  image reconstruction using Siemens tool
void Simens_recon(int niterations,int nsubsets)
{

  string inputFolder_mcs = "" ;
  string inputFolder_comm = "" ;

  //sinogram file
  ////float formats:
  string prompt_sino="";
  string random_sino="";

  //--- Norm file for measurement data
  string norm_sino= "";

  //...attenuation sinogram generated by forward projection by Siemens tools;
  string atte_sino= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/common_sino_files/att.fs";//float format

  // scatter with scatter modual;
  string scatter_sino_scaled = "";
  // scatter file: with detetion module; norm: with detector modual
  string reconstructe_img= "";
 
  stools->SIEMENS_RECO_W3(prompt_sino, random_sino, norm_sino,  atte_sino, scatter_sino_scaled, niterations, nsubsets, reconstructe_img);





  cout <<endl<<endl;
  cout << "image reconstruction finished :image saved path:"<< endl;
  cout <<reconstructe_img <<endl;
  cout << "***********************************************************************************" << endl;


  cout <<endl<<endl;
  cout << "******************"<<endl;
}






