/*
 * Description: This macro is used for the image reconstruction using the Siemens reconstruction method. 
 *
 *
 * Input: 
 *
 *
 * Procedure:
 *
 *
 * Functions:
 *
 *
 * Editor: Bo Ma
 *
 * Date: 2018.12.07
 *
 */




//void Image_reconstruction_Simens( string patient_name,string inputFolder, string path_norm_sino,string frame_time)
void Image_reconstruction_Simens()
{

  //// ********************1: with detector modual*************************

  string prompt_sino="/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/merged_with_detector_modual/true_plus_scatter.fs";
  string random_sino="/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/common_sino_files/random.fs";

  //--- Norm file for measurement data
  string norm_sino= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/norm_with_detection_modual/norm_sino_320_192_with_detection_modual.fs";

  //...attenuation sinogram generated by forward projection by Siemens tools;
  string atte_sino= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/XB1BN305N-BI/atten/XB1BN305N-BI_AttenMap_HeadOnly.a";//float format

  // scatter with scatter modual;
  //string scatter_sino_scaled = "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/run_5000_with_detector_modual/scatter_scaled_normed.fs";
  string scatter_sino_scaled = "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/merged_with_detector_modual/scatter_normed.fs";
  // scatter file: with detetion module; norm: with detector modual
  //string reconstructe_img= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/img/recon_img_scat_sino_with_detec.i";
  string reconstructe_img= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/img/recon_img_merged.i";

  int nsubsets=2;
  int niterations=32;

  Simens_recon(prompt_sino, random_sino, norm_sino, atte_sino ,scatter_sino_scaled ,reconstructe_img,  niterations, nsubsets);


  // ********************2: without detector modual*************************

 /* scatter_sino_scaled = "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/run_5000_no_detector_modual/scatter_scaled_normed.fs";*/
  //reconstructe_img= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/img/recon_img_scat_sino_no_detec.i";


  //Simens_recon(prompt_sino, random_sino, norm_sino, atte_sino ,scatter_sino_scaled ,reconstructe_img,  niterations, nsubsets);


  /*////// ******************** 3: without detector modual,using the true sino only**************************/

   //string prompt_sino="/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/run_5000_no_detector_modual/true.fs";
  //string random_sino="/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/common_sino_files/random.fs";

  ////--- Norm file for measurement data
  //string norm_sino= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/norm_no_detection_modual/norm_sino_320_192_no_detection_modual.fs";

  ////...attenuation sinogram generated by forward projection by Siemens tools;
  //string atte_sino= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/XB1BN305N-BI/atten/XB1BN305N-BI_AttenMap_HeadOnly.a";//float format

  //// scatter with scatter modual;
  //string scatter_sino_scaled = "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/common_sino_files/scatter.fs";
  //// scatter file: with detetion module; norm: with detector modual
  //string reconstructe_img= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/run_5000_no_detector_modual/true.i";

  //int nsubsets=2;
  //int niterations=32;

  //Simens_recon(prompt_sino, random_sino, norm_sino, atte_sino ,scatter_sino_scaled ,reconstructe_img,  niterations, nsubsets);



/*  ////// ******************** 4: with detector modual,using the true sino only**************************/

   //string prompt_sino="/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/merged_with_detector_modual/true.fs";
  //string random_sino="/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/common_sino_files/random.fs";

  ////--- Norm file for measurement data
  //string norm_sino= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/norm_with_detection_modual/norm_sino_320_192_with_detection_modual.fs";

  ////...attenuation sinogram generated by forward projection by Siemens tools;
  //string atte_sino= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/XB1BN305N-BI/atten/XB1BN305N-BI_AttenMap_HeadOnly.a";//float format

  //// scatter with scatter modual;
  //string scatter_sino_scaled = "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/common_sino_files/scatter.fs";
  //// scatter file: with detetion module; norm: with detector modual
  //string reconstructe_img= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/img/recon_img_true.i";

  //int nsubsets=2;
  //int niterations=32;

  /*Simens_recon(prompt_sino, random_sino, norm_sino, atte_sino ,scatter_sino_scaled ,reconstructe_img,  niterations, nsubsets);*/



  gApplication->Terminate();


}



//  image reconstruction using Siemens tool
void Simens_recon(string prompt_sino, string random_sino, string norm_sino, string atte_sino ,string scatter_sino_scaled ,string reconstructe_img, int niterations,int nsubsets)
{

  stools->SIEMENS_RECO_W3(prompt_sino, random_sino, norm_sino,  atte_sino, scatter_sino_scaled, niterations, nsubsets, reconstructe_img);



  cout <<endl<<endl;
  cout << "image reconstruction finished :image saved path:"<< endl;
  cout <<reconstructe_img <<endl;
  cout << "***********************************************************************************" << endl;


  cout <<endl<<endl;
  cout << "******************"<<endl;
}






