/*
 * Description: This macro is used for the image reconstruction using the Siemens reconstruction method. 
 *
 *
 * Input: 
 *
 *
 * Procedure:
 *
 *
 * Functions:
 *
 *
 * Editor: Bo Ma
 *
 * Date: 2018.12.07
 *
 */







//void Image_reconstruction_Simens( string patient_name,string inputFolder, string path_norm_sino,string frame_time)
void Image_reconstruction_Simens()
{

  /* string patient_name="XB1BN286N-BI-09";*/
  //string inputFolder="/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/Random-OFOV-activity-C11-2016-09-08/"+patient_name+"/";
  /*string frame_time="0-1222";*/

  //string path_norm_sino= inputFolder+"norm/PSNorm-170720_STD_norm.fs";

  int nsubsets=2;
  int niterations=32;
  //int niterations=64;


  //Simens_recon(patient_name,frame_time,inputFolder,path_norm_sino, niterations, nsubsets);
  Simens_recon_single( niterations, nsubsets);

  gApplication->Terminate();


}



void Simens_recon(string patient_name,string frame_time,string inputFolder,string path_norm_sino,int niterations,int nsubsets)
{


  string basename = patient_name+"_"+frame_time;  
  string basename_simu = basename+"_gpuSimu"; 

  //sinogram files:
  string prompt_sino=inputFolder + "sinos/range_"+frame_time+"_prompt.fs";//integer format
  string random_sino=inputFolder +"sinos/range_"+frame_time+"_vrr.fs";//float format

  //--- Norm file for measurement data
  //string norm_sino= inputFolder+"norm/PSNorm-170720_STD_norm.fs";
  string norm_sino= path_norm_sino;

  //...attenuation sinogram generated by forward projection by Siemens tools;
  string atte_sino= inputFolder + "atten/AttenMap_for_reco.a";//float format

  string scatter_sino_sss = inputFolder + "scatterSSS/range_"+frame_time + "_scal_scat.fs" ;


  string simufolder=inputFolder+"scatterMCS/";
  string scatter_sino_mcs = simufolder +  "normed_scaled_scatter.fs" ;


  //the reconstructed image will stored in the path bellow.
  string reconstructe_img_mcs=inputFolder + "img/mcs/"+ basename_simu +".i";
  string reconstructe_img_sss=inputFolder + "img/sss/"+ basename+".i";

  string reconstructe_log=inputFolder + "img/image_reconstruct_log";



  ofstream of;
  of.open(reconstructe_log.c_str(),std::ofstream::out | std::ofstream::app);


  of<< "Simens tool: OSEM Iteration number: " << niterations<< "subsets: "<<nsubsets<<endl;

  of <<endl<<endl;
  of << "stools->SIEMENS_RECO_W3(prompt_sino, random_sino, norm_sino,  atte_sino, scatter_sino_scaled_mcs,niterations, nsubsets, reconstructe_img) " << endl;


  string scatter_sino_scaled;
  string reconstructe_img;

  for(int i=0;i<2;i++)
  {
    // 1: sss reconstruction
    if(i==0)
    {
      scatter_sino_scaled=scatter_sino_sss;
      reconstructe_img=reconstructe_img_sss;

      cout<<"sss reconstr"<<endl;
      continue;

    }

    // 2: mcs reconstruction
    if(i==1) 
    {
      scatter_sino_scaled=scatter_sino_mcs;
      reconstructe_img=reconstructe_img_mcs;
      cout<<"sss reconstr"<<endl;
      //continue;

    }
    stools->SIEMENS_RECO_W3(prompt_sino, random_sino, norm_sino,  atte_sino, scatter_sino_scaled, niterations, nsubsets, reconstructe_img);

  }




  cout <<endl<<endl;
  cout << "image reconstruction finished :image saved path:"<< endl;
  cout <<reconstructe_img <<endl;
  cout << "***********************************************************************************" << endl;
  of<<endl<<endl;
  of<< "image reconstruction finished : image saved path:"<< endl;
  of<<reconstructe_img <<endl;
  of<< "***********************************************************************************" << endl;



  //....end of image reconstruction///////////////////////////////////////////////////////////

  of.close();


  cout <<endl<<endl;
  cout << "******************"<<endl;
}



//void Simens_recon_single(string patient_name,string frame_time,string inputFolder,string path_norm_sino,int niterations,int nsubsets)
void Simens_recon_single(int niterations,int nsubsets)
{

  //string inputFolder_mcs = "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/sphere_phantom_simu/1_fov/scatterMCS/" ;
  string inputFolder_mcs = "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/XB1BN310N-BI/XB1BN310N-BI-01/scatterMCS/merge_36800/" ;
  string inputFolder_comm = "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/" ;

  //sinogram files:
  //string prompt_sino=inputFolder_mcs + "run_5000_with_detector_modual/true.fs";//integer format
  //string prompt_sino=inputFolder_mcs + "XB1BN310N-BI-01_0-1800_gpuSimu_true_scatter_sino.fs";//integer format
  string prompt_sino=inputFolder_mcs + "XB1BN310N-BI-01_0-1800_gpuSimu_scat_without_scaled.fs";//integer format
  //string prompt_sino=inputFolder + "att_forward_projection_with_gaps.fs";//integer format
  //string prompt_sino=inputFolder + "att_forward_projection_with_gaps_bad_plane_cor.fs";//integer format
  //string prompt_sino= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/scatterMCS/merged_sino/norm_acq_gpuSimu_0_true.fs";//integer format
  string random_sino=inputFolder_comm +"common_sino_files/random.fs";//float format

  //--- Norm file for measurement data
  //string norm_sino= inputFolder +"common_sino_files/norm_ones.fs";
  string norm_sino= inputFolder_comm + "norm_sino_320_192.fs";
  //string norm_sino= inputFolder +"common_sino_files/norm_ones_with_gap_bad_plane_corr.fs";
  //string norm_sino= inputFolder +"/norm_sino_320_192.fs";

  //...attenuation sinogram generated by forward projection by Siemens tools;
  //string atte_sino= inputFolder_comm +"common_sino_files/att.fs";//float format
  //string atte_sino= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/XB1BN305N-BI/atten/XB1BN305N-BI_AttenMap_HeadOnly.a";//float format
  string atte_sino= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/XB1BN310N-BI/XB1BN310N-BI-01/atten/AttenMap_for_reco.a";//float format


  string scatter_sino_scaled = inputFolder_comm +"common_sino_files/scatter.fs";
  //string scatter_sino_scaled = inputFolder_mcs +"XB1BN310N-BI-01_0-1800_gpuSimu_scat_without_scaled.fs";

  ////the reconstructed image will stored in the path bellow.
  //string reconstructe_img=inputFolder_mcs + "true_norm_320_att.i";
  string reconstructe_img=inputFolder_mcs + "scatter_norm_320_att.i";
  //string reconstructe_img=inputFolder_mcs + "img/with_dectection_modual_norm_32cm_att.i";
  //string reconstructe_img=inputFolder + "img/reconstructed_img_fwp_to_bwp_fwp_Norm_with_gaps.i";
  //string reconstructe_img=inputFolder + "img/reconstructed_img_new_normed_to_one_2.i";
  //string reconstructe_img= "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/test/true.i";

  stools->SIEMENS_RECO_W3(prompt_sino, random_sino, norm_sino,  atte_sino, scatter_sino_scaled, niterations, nsubsets, reconstructe_img);





  cout <<endl<<endl;
  cout << "image reconstruction finished :image saved path:"<< endl;
  cout <<reconstructe_img <<endl;
  cout << "***********************************************************************************" << endl;


  cout <<endl<<endl;
  cout << "******************"<<endl;
}

