/*
 * There are four bad planes in the sino, this is used to set the bad planes with the value of the neighbouring planes.
 *
 * Editor: Bo Ma
 */

void sino_bad_planes_cor()
{

  // sino needed to correct bad planes
  //
  string base_folder = "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/XB1BN304N-BI/30min-data_0-30/scatterMCS/";
  string part_name_sino = "scatter_multi";
  string path_input_sino = base_folder + part_name_sino +".fs";

  // bad plane sino, in which all points are set zero while the points in the bad plane is set one.
  string path_bad_plane_sino = "/data/PET/mr_pet_temp/Ma/software/data/gpupet/phantom/cylinder_phantom_norm_file_mcs/common_sino_files/bad_planes_sino.fs" ;

  string part_bad_plane ="_bad_plane_cor";
  string saved_sino = base_folder + part_name_sino + part_bad_plane +".fs";

set_bad_plane(path_input_sino,path_bad_plane_sino, saved_sino);

gApplication->Terminate();


}

/*
 * used to correct the bad planes in the sinograme generated by brainPET.
 * the bad points are setted with the average value of planes of the i+1 and i-1
 *
 *
 * */

void set_bad_plane(string path_input_sino,string path_bad_plane_sino, string path_saved_sino)
{

  //class including all the basic information of the MRPET.
  MRPET_dump *dump = new MRPET_dump();	

  ///---measurement data, correction of random and scatter//////////////////////////////////////////////////
  BrainPET_Sinograms* sino_input_1=new BrainPET_Sinograms(dump,"sino_norm");  
  BrainPET_Sinograms* sino_input_2=new BrainPET_Sinograms(dump,"temp");

  bool is_int=false;
  sino_input_1->read_flatSinogram(path_input_sino,is_int);
  sino_input_2->read_flatSinogram(path_bad_plane_sino,is_int);

  cout<<" the total events of sino_1 is: " << sino_input_1->get_n_Events()<< endl;
  cout<<" the total events of sino_2 is: " << sino_input_2->get_n_Events()<< endl;

  int n_planes=sino_input_1->get_n_planes(); 
  int n_views=sino_input_1->get_n_views(); 
  int n_projs=sino_input_1->get_n_projs(); 

  for (int i_plane=0;i_plane<n_planes;i_plane++)
  {
    for(int i_view=0;i_view<n_views;i_view++)
    {
      for(int i_proj=0;i_proj<n_projs;i_proj++)
      {

        int addr = i_plane*n_views*n_projs + i_view*n_projs + i_proj;
        //get the address in the sino
        //dump->proj_to_addr(i_view, i_proj, i_plane, addr);

        float sino_value_2=sino_input_2->get_event_from_address (addr);

        if(sino_value_2>0)
        {

          int addr_1 = (i_plane-1)*n_views*n_projs + i_view*n_projs + i_proj;
          int addr_2 = (i_plane+1)*n_views*n_projs + i_view*n_projs + i_proj;

          float ave_value=0;
          float sino_value_down = 0;
          float sino_value_up=0;

          if(i_plane>0 && i_plane<(n_planes-1))
          {
            sino_value_down = sino_input_1->get_event_from_address ( addr_1);
            sino_value_up=sino_input_1->get_event_from_address ( addr_2);

          }
          else if(i_plane==0)
          {
            sino_value_up=sino_input_1->get_event_from_address ( addr_2);
            sino_value_down=sino_value_up;


          }
          else if(i_plane==(n_planes-1))
          {
            sino_value_down = sino_input_1->get_event_from_address ( addr_1);
            sino_value_up=sino_value_down;

          }

          ave_value =(sino_value_down+sino_value_up)/2;



            sino_input_1->set_event_at_address (addr, ave_value);

        }

      }
    }
  }


  cout<<" the total events of merged sino is: " << sino_input_1->get_n_Events()<< endl;

  sino_input_1->write_flat_sinograms(path_saved_sino,is_int);


  if(sino_input_1!=NULL)
  {
    delete sino_input_1;
    sino_input_1=NULL;

  }

  if(sino_input_2!=NULL)
  {
    delete sino_input_2;
    sino_input_2=NULL;

  }
  if(dump!=NULL)
  {
    delete dump;
  }


}
